[build]
  base = "08_Deployment/Frontend"
  command = "pnpm install --no-frozen-lockfile && pnpm run build"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "FASTAPI_PORT,ALLOWED_ORIGINS"

[[plugins]]
  package = "@netlify/plugin-nextjs"
